"use strict";

window.alert("Oi");
alert("Oi");
window.console.error("[ERROR]");
console.error("[ERROR]");
var pessoa = Object();
pessoa;
var lista = Array();
lista;
lista = Array("a", "b", "c");
lista;
var a = String();
a;
String(42);
String(true);
String(false);
String({});
String(console.log);
Number("42");
Number.isInteger(4.5);
Number.isInteger(4);
Date();
Math.PI;
Math.pow(2, 10);
Math.sqrt(144);
Math.random();